feedo/blog/urls.py
from django.urls import  path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.PostListView.as_view(), name='post_list'),
	path('tag/<slug:tag_slug>/',views.PostListView.as_view(), name='post_list_by_tag'),
	path('<int:year>/<int:month>/<int:day>/<slug:post>',views.post,name='post'),
	path('<int:post_id>/share/',views.post_share,name='post_share')
]

feedo/feedo/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog'))
]

handler404 = 'blog.views.page_not_found'

feedo/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager

# менеджер для получения опубликованных постов
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):
	STATUS_CHOICES = (
		('draft','Draft'),
		('published','Published')
	)

	# поля модели

	title 	= models.CharField(max_length=50)
	slug 	= models.SlugField(max_length=50, unique_for_date='publish')
	author 	= models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_post')
	content = models.TextField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	publish = models.DateTimeField(default=timezone.now)
	updated = models.DateTimeField(auto_now=True)
	status 	= models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

	# managers

	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()

	class Meta:
		ordering = ('-publish',)

	def get_absolute_url(self):
		return reverse('blog:post', args=[
			self.publish.year,
			self.publish.month,
			self.publish.day,
			self.slug
		])

	def get_comments_number(self):
		return len(self.comments.filter(active=True))

	def get_excerpt(self):
		content = self.content
		return content[:250]+('...' if len(content)>100 else '')

	def __str__(self):
		return self.title


class Comment(models.Model):
	post = models.ForeignKey(Post,
		on_delete=models.CASCADE,
		related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return f'Comment by {self.name} on {self.post}'

feedo/blog/forms.py
from django import forms
from .utils import get_input_attrs
from .models import Comment

class EmailPostForm(forms.Form):
	attrs = {'class':'form-control'}

	name = forms.CharField(max_length=25,widget=forms.TextInput(attrs=get_input_attrs('Name')))
	email = forms.EmailField(widget=forms.EmailInput(attrs=get_input_attrs('Email')))
	to = forms.EmailField(widget=forms.EmailInput(attrs=get_input_attrs('To')))
	comments = forms.CharField(required=False,widget=forms.Textarea(attrs=get_input_attrs('Comments')))

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','email','body')
		widgets = {
			'name': forms.TextInput(attrs=get_input_attrs('Name')),
			'email': forms.EmailInput(attrs=get_input_attrs('Email')),
			'body': forms.Textarea(attrs=get_input_attrs('Comment',classes=['comment-textarea']))
		}

feedo/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.template import RequestContext
from django.views.generic import ListView
from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm


class PostListView(ListView):
	paginate_by = 3
	template_name = 'blog/index.html' 

	def get_queryset(self):
		queryset = Post.published.all()
		if self.kwargs.get('tag_slug'):
			tag = get_object_or_404(Tag, slug=self.kwargs['tag_slug'])
			queryset = queryset.filter(tags__in=[tag])
		return queryset 

	def get(self,request,*args,**kwargs):
		context = locals()
		context['tag'] = self.kwargs.get('tag_slug')
		context['posts'] = self.get_queryset()
		if request.GET.get('from'):
			context['from'] = get_object_or_404(Post,id=request.GET['from'],status='published') 

		return render(request,self.template_name,context)



def post(request,post,year,month,day):

	post = get_object_or_404(
		Post,
		slug=post,
		status='published',
		publish__year=year,
		publish__month=month,
		publish__day=day
	) 

	post_tag_ids = post.tags.values_list('id',flat=True)
	similar_posts = Post.published.filter(tags__in=post_tag_ids)\
		.exclude(id=post.id).annotate(same_tags=Count('tags'))\
		.order_by('-same_tags','-publish')[:4]

	comments = post.comments.filter(active=True)
	new_comment = None

	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()

	return render(
		request, 
		'blog/post.html', 
		{
			'id':id,
			'post':post,
			'comments':comments,
			'new_comment':new_comment,
			'comment_form':comment_form,
			'similar_posts':similar_posts
		}
	)


def post_share(request, post_id):

	post = get_object_or_404(Post,id=post_id,status='published')
	sent = False

	if request.method == 'POST':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = f'{cd["name"]} reccomends you read "{post.title}"'
			message = f'Read "{post.title} at {post_url}"\n\n' \
				f'{cd["name"]}\'s comments: {cd["comments"]}'
			send_mail(
				subject,message,
				from_email=getattr(settings,'DFAULT_FROM_EMAIL','nsit2002@gmail.com'),
				recipient_list=[cd['to']]
			)
			sent = True
	else:
		form = EmailPostForm()

	return render(request, 'blog/post_share.html', {'post':post,'form':form,'sent':sent})


def page_not_found(request, exception=None):

    # return render(request, '404.html')
    return redirect('/')

feedo/templates/blog/index.html
{% extends "../origin/base.html" %}
{% load blog_tags %}
{% block content %}
	<div class="mb-3">
	 	<div>
			<div class="mb-3">
				{% if from %}
					<a class="btn btn-primary btn-sm mb-3" href="{{ from.get_absolute_url }}">
						<<< Back to reading	
					</a>
				{% endif %}
				{% if tag %}
					<div class="fs-3 mb-3">
						Posts tagged with "<span class="fw-bold">{{ tag }}</span>":
					</div>
				{% endif %}
				<div>
					{% get_most_used_tags as most_used_tags %}
					{% for tag in most_used_tags %}
					<a href="{% url "blog:post_list_by_tag" tag.slug %}" class="btn btn-dark btn-sm">{{tag}}</a>
					{% endfor %}
				</div>
		 	</div>
			{% if posts %}
				{% for post in posts %}
					<div class="card bg-dark text-white mb-2">
						<div class="p-3">
							<a  class="text-white" href="{{ post.get_absolute_url }}">
								<h5>
									{{ post.title }}
								</h5>
							</a>
							<div>
								{{ post.content|markdown|truncatewords_html:30 }}
							</div>
							{% if post.tags.all %}
								<div class="mt-3">
									{% for tag in post.tags.all %}
										<a href="{% url "blog:post_list_by_tag" tag.slug %}" class="badge bg-warning text-dark text-decoration-none">{{ tag }}</a>
									{% endfor %}
								</div>
							{% endif %}
						</div>
					</div>
				{% endfor %}
			{% else %}
				<h3>Sorry, there is not content for this blog</h3>
			{% endif %}
		</div>
		{% include './pagination.html' with page=page_obj %}
	</div>
{% endblock %}

feedo/templates/blog/pagination.html
<div>
	{% if page.has_previous or page.has_next %}
	 	{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}" class="m-2 btn btn-info">Previous</a>
		{% endif %}
		Page 
		{{ page.number }}
		of
		{{ page.paginator.num_pages }}
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}" class="m-2 btn btn-info">Next</a>
		{% endif %}
	{% endif %}
</div>

feedo/templates/blog/post.html
{% extends '../origin/base.html' %}
{% load blog_tags %}
{% block content %}
	<div>
		<div>
			<div>
				<a class="btn btn-primary btn-sm" href="/">
					<<< Back
				</a>
				<div class="my-4">
					<h2 class="mb-0">{{ post.title }}</h2>
					<small class="text-muted">{{ post.created }}</small>
				</div>
				<div class="mb-2">
					{% for tag in post.tags.all %}
						<a href="{% url "blog:post_list_by_tag" tag.slug %}?from={{ post.id }}" class="btn btn-dark btn-sm">{{ tag }}</a>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="mb-2 bg-white p-2">
				{{ post.content|markdown }}
		</div>
		<div class="d-flex justify-content-end">
			<div>
				<a class="btn btn-success" href="#">Like</a>
				<a class="btn btn-primary" href="{% url "blog:post_share" post.id %}">Share</a>
			</div>
		</div>
		<div class="my-3">
			{% with comments.count as total_comments %}
				<small class="text-muted">{{ total_comments}} comment{{ total_comments|pluralize }}</small>	
			{% endwith %}
			<div class="mb-4 mt-3">
				{% for comment in comments %}
					<div class="card p-2 mb-2">
						<div>
							<span class="fw-bold">{{ comment.name }}</span> 
							<small class="text-muted">{{ comment.created|date:" j.m.Y \a\t H:i" }}</small>
						</div>
						{{ comment.body }}
					</div>
				{% empty %}
					<p>There are no comments yet</p>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}
{% block sidebar_extra %}
	{% if similar_posts %}
		<div class="p-2 card mb-2">
			<h5><i class="fa-solid fa-angles-right"></i> Related posts</h5>
			{% for post in similar_posts %}
				<a class="card bg-light p-1 mt-2 text-reset text-decoration-none" href="{{post.get_absolute_url}}">
					<span class="text-decoration-underline">{{post.title}}</span>
					<div class="text-muted">
						<small>
							{{post.created|date:"j.mY \a\t H:i"}}
						</small>
					</div>
				</a>
			{% endfor %}
		</div>
	{% endif %}
	<div class="p-2 card mb-2">
		{% if new_comment %}
			<div class="alert alert-success">
				Your comment has been added
			</div>
		{% else %}
			<form method="POST">
				<h5 class="m-0 mb-3"><i class="fa-solid fa-thumbtack"></i> Please leave comment</h5>
				<div class="mb-3">
					{{comment_form.name}}
				</div>
				<div class="mb-3">
					{{comment_form.email}}
				</div>
				<div class="mb-3">
					{{comment_form.body}}
				</div>
				{% csrf_token %}
				<input class="btn btn-primary w-100" type="submit" value="Add Comment">
			</form>
		{% endif %}
	</div>
{% endblock %}

feedo/templates/blog/post_share.html
{% extends '../origin/base.html' %}
{% block content %}
	<div class="container my-5">
		<div class="user-select-none card bg-dark text-white" style="max-width: 400px; margin: 0 auto">
			<div class="p-4">
				<h1 class="text-center">FeeDo.</h1>
				<div class="mb-3">
					<a  class="text-white" href="{{ post.get_absolute_url }}"><<< Back to post</a>
				</div>
				<h4 class="mb-3">Share post "{{ post.title }}"</h4>
				{% if sent %}
					<div class="alert alert-success" role="alert"><i class="fas fa-check-circle">
						</i> Mail sent successfully!
					</div>
				{% else %}
					<form method="POST">
						{% for field in form %}
							<div class="mb-2">
								{{ field.errors }}
								{{ field.label_tag }} {{ field }}
							</div>
						{% endfor %}
						{% csrf_token %}
						<div class="mt-3">
							<input class="btn btn-primary" type="submit" value="Send">
						</div>
					</form>	
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

feedo/templates/origin/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static "css/blog.css" %}">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body class="bg-light">
	<div class="wrapper mb-5">
		{% include './header.html' %}
		<div class="container">
			<div class="d-block d-md-flex" style="gap: 0.5em;">
				<div class="w-100">
					{% block content %}
					{% endblock %}
				</div>
				<div>
					<div class="sidebar">
						<div class="p-2 card mb-2">
							<h5><i class="fa-solid fa-fire"></i> Most commented</h5>
							{% get_most_commented_posts as most_commented_posts %}
							{% for post in most_commented_posts %}
								<a class="card bg-light p-1 mt-2 text-reset text-decoration-none" href="{{post.get_absolute_url}}">
									<span class="d-flex justify-content-between">
										<span class="text-decoration-underline mr-3">
											{{post.title}}	
										</span>
										<span class="text-muted">
											{{ post.get_comments_number }} <i class="fa-solid fa-comment"></i>
										</span>
									</span>
									<div class="text-muted">
										<small>
											{{post.created|date:"j.mY \a\t H:i"}}
										</small>
									</div>
								</a>
							{% endfor %}
						</div>
						{% block sidebar_extra %}
						{% endblock %}
					</div>
				</div>
			</div>
		</div>
		<div class="container my-5">
			<div class="text-center text-muted">
				<small>
					&copy; Lama's ~
					total {% total_posts %} posts
				</small>
			</div>
		</div>
	</div>
</body>
</html>

feedo/templates/origin/header.html
<header class="container my-3">
	<div class="card p-2 bg-dark text-white">
		<div class="d-flex justify-content-between align-items-center">
			<a class="fs-2 text-reset text-decoration-none" href="/">
				<i class="fa-solid fa-message"></i> FeeDo.
			</a>
			<div class="d-flex" style="gap: 0.5em">
				<div class="input-group">
					<span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-magnifying-glass"></i></span>
					<input type="text" class="form-control" placeholder="Search" aria-label="Username" aria-describedby="basic-addon1">
				</div>
				<div>
					<a href="#" class="btn btn-success">Donation</a>
				</div>
			</div>
		</div>
	</div>
</header>